blank_issues_enabled: false
contact_links:
  - name: üí¨ Questions & Discussions
    url: https://t.me/esphome_lvgl_chats/5
    about: For questions, suggestions, and general discussions
  - name: üí¨ –í–æ–ø—Ä–æ—Å—ã –∏ –û–±—Å—É–∂–¥–µ–Ω–∏—è
    url: https://t.me/esphome_lvgl_chats/10
    about: –î–ª—è –≤–æ–ø—Ä–æ—Å–æ–≤, –ø—Ä–µ–¥–ª–æ–∂–µ–Ω–∏–π –∏ –æ–±—â–∏—Ö –æ–±—Å—É–∂–¥–µ–Ω–∏–π
  - name: üí° Ideas / –ò–¥–µ–∏
    url: https://t.me/esphome_lvgl_chats/74
    about: Suggest new features or improvements / –ü—Ä–µ–¥–ª–æ–∂–∏—Ç—å –Ω–æ–≤—ã–µ —Ñ—É–Ω–∫—Ü–∏–∏ –∏–ª–∏ —É–ª—É—á—à–µ–Ω–∏—è
